### ISSUE TITLE
AT4

### ISSUE THREAD

**Issue by ccpandhare** [kunal-mohta/frontend-102#1]
[This](https://github.com/kunal-mohta/frontend-102/blob/master/A/4.js#L3-L5) is correct. but could you do it without declaring a new function?

**Comment by ccpandhare** [comment]
How about....
```js
module.exports = require('base-64').encode
```
?
;)

**Comment by kunal-mohta** [comment]
Oh! Haven't done that before.
Very Nice! 👍

**Comment by kunal-mohta** [comment]
Implemented this.
Closing now.
